/**
 * Auto-generated by gltfjsx, cleaned for r3f idioms.
 * Source: public/models/brain-lowpoly.glb
 * License: CC Attribution (get3dmodels.com)
 */
import { Center, useGLTF } from '@react-three/drei';
import { useMemo, useRef, type ReactNode } from 'react';
import type { Group, Mesh, MeshStandardMaterial } from 'three';

import {
	BRAIN_NORM_DIVISOR,
	CENTER_DIVISOR,
	LCG_MODULUS,
	LCG_MULTIPLIER,
	SHUFFLE_SEED
} from '../../../constants';

type GLTFBrain = {
	materials: { 'Brain pink': MeshStandardMaterial };
	nodes: { BRAIN: Mesh };
};

type BrainModelProps = {
	children?: ReactNode;
	scale?: number;
} & Record<string, unknown>;

/**
 * Brain geometry is ~214 units wide, ~180 tall, ~172 deep.
 * We normalize to ~1 unit radius so it fits the scene.
 */
const NORMALIZE_SCALE = 1 / BRAIN_NORM_DIVISOR;

export const BrainModel = ({ children, scale, ...props }: BrainModelProps) => {
	const groupRef = useRef<Group>(null);
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
	const { nodes } = useGLTF(
		'/models/brain-lowpoly.glb'
	) as unknown as GLTFBrain;

	return (
		<group ref={groupRef} {...props} dispose={null}>
			<Center scale={(scale ?? 1) * NORMALIZE_SCALE}>
				<mesh geometry={nodes.BRAIN.geometry}>{children}</mesh>
			</Center>
		</group>
	);
};

/** Get the brain geometry for sampling vertex positions (memory points, etc.) */
export const useBrainGeometry = () => {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
	const { nodes } = useGLTF(
		'/models/brain-lowpoly.glb'
	) as unknown as GLTFBrain;

	return nodes.BRAIN.geometry;
};

/** Sample N random positions from brain surface, normalized to ~1 unit radius */
export const useBrainSurfacePoints = (count: number) => {
	const geo = useBrainGeometry();

	return useMemo(() => {
		const pos = geo.attributes.position;
		if (!pos) {
			return [];
		}

		// Compute center for offsetting
		geo.computeBoundingBox();
		const bounds = geo.boundingBox;
		if (!bounds) {
			return [];
		}
		const centerX = (bounds.min.x + bounds.max.x) / CENTER_DIVISOR;
		const centerY = (bounds.min.y + bounds.max.y) / CENTER_DIVISOR;
		const centerZ = (bounds.min.z + bounds.max.z) / CENTER_DIVISOR;

		const indices: number[] = [];
		for (let idx = 0; idx < pos.count; idx++) {
			indices.push(idx);
		}

		// Deterministic shuffle (seeded)
		let seed = SHUFFLE_SEED;
		for (let idx = indices.length - 1; idx > 0; idx--) {
			seed = (seed * LCG_MULTIPLIER + 0) % LCG_MODULUS;
			const swapIdx = seed % (idx + 1);
			const tmp = indices[swapIdx] ?? 0;
			indices[swapIdx] = indices[idx] ?? 0;
			indices[idx] = tmp;
		}

		const picked = indices.slice(0, Math.min(count, pos.count));

		const toTuple = (idx: number) =>
			[
				(pos.getX(idx) - centerX) * NORMALIZE_SCALE,
				(pos.getY(idx) - centerY) * NORMALIZE_SCALE,
				(pos.getZ(idx) - centerZ) * NORMALIZE_SCALE
			] satisfies [number, number, number];

		return picked.map(toTuple);
	}, [geo, count]);
};

useGLTF.preload('/models/brain-lowpoly.glb');
